id: P007878
initial_creation_type: ocr
source_metadata:
  id: bdr:W29157
  title: གསུང་འབུམ། བློ་བཟང་དཔལ་ལྡན་ཆོས་ཀྱི་རྡོ་རྗེ
  author: ''
  volumes:
    b09f948703fd4e4fb4af676a9b545ce3:
      image_group_id: I1KG1342
      title: ''
      volume_number: 1
      total_pages: 744
    58ce3f8f74d74d03aab6d9cb50e60ea3:
      image_group_id: I1KG1343
      title: ''
      volume_number: 2
      total_pages: 748
    6ebc27e9c3034d678b7dd0aefc351326:
      image_group_id: I1KG1344
      title: ''
      volume_number: 3
      total_pages: 524
    d89d0548a272498f9f57df430cb2caa7:
      image_group_id: I1KG1345
      title: ''
      volume_number: 4
      total_pages: 512
    b59bff112fca43c189108ca51d95440a:
      image_group_id: I1KG1346
      title: ''
      volume_number: 5
      total_pages: 580
    b8069493abb5423ca3aeb0a4ef667aa9:
      image_group_id: I1KG1347
      title: ''
      volume_number: 6
      total_pages: 488
ebook_metadata:
  title: གསུང་འབུམ། བློ་བཟང་དཔལ་ལྡན་ཆོས་ཀྱི་རྡོ་རྗེ
  author: ''
  sku: P007878
  cover: cover.jpg
  layers:
  - pagination
